#!/bin/bash

set -o nounset
set -o errexit

_prepare()
{
	local name=$1
	local version=$2
	local pkg=$(basename $3)

	local a p

	if [[ ! -d ${name}-${version} ]]; then
		if [[ -f $SRC/$pkg ]]; then
			tar xvf $SRC/$pkg
		elif [[ -d $SRC/$pkg ]]; then
			cp -a $SRC/$pkg ${name}-${version}
		fi
		# patches
		for p in `find $SRC/patches/${name}/${version} -name "*.patch"`; do
			patch -d ${name}-${version} -p1 < $p
		done
	fi


	cd ${name}-${version}
}

. $TOP/scripts/$1.stage || { echo "ERROR on stage $1"; exit 1; }

# ex: ts=4 sw=4 ft=sh
